### ISSUE TITLE
Duplicate New Application Notifications

### ISSUE THREAD

**Issue by eeverett91** [eveseat/seat#884] opened 2023-03-10 23:54 UTC
* **Problem**: _Whats wrong?_
* The New Application discord notification was sent 5 times when someone applied to corporation.
 
* **Expected**: _What did you expect to happen?_
* Notification only sent once.
 
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* https://i.imgur.com/4zkssoN.png
 
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SeAT API v4.9.0
SeAT Console v4.8.0
SeAT Eve API v4.18.1
SeAT Notifications v4.3.3
SeAT Services v4.2.1
SeAT Web v4.19.3

**Comment by eeverett91** [comment] 2023-03-10 23:58
Perhaps its noteworthy that I have tokens for 5 characters with the personnel manager role in SeAT. Maybe it's sending one per toon/token that receives the notification?

**Comment by Crypta-Eve** [comment] 2023-03-11 00:00
> Perhaps its noteworthy that I have tokens for 5 characters with the personnel manager role in SeAT. Maybe it's sending one per toon/token that receives the notification?

Yes that is correct. For each affiliated token we will directly forward the notification. I suggest reducing down to only one token.

**Comment by eeverett91** [comment] 2023-03-11 00:04
I think I'll disable the notification. The tokens belong to toons from multiple players; recruiters + CEO + Directors. I would prefer not to remove their tokens.

Perhaps a feature request for the future could be to look for duplicate notifications and only send one?

**Comment by Crypta-Eve** [comment] 2023-03-11 00:47
> I think I'll disable the notification. The tokens belong to toons from multiple players; recruiters + CEO + Directors. I would prefer not to remove their tokens.
> 

You don't need to remove their tokens, just not include them in the notification groups affiliation list. Likewise if you have in the affiliation the corp, that matches all toons of the corp. So just place day the CEO in the affiliation. 


> Perhaps a feature request for the future could be to look for duplicate notifications and only send one?

It's something we should look into yes, but deduplicating is not always trivial.

**Comment by eeverett91** [comment] 2023-03-11 03:19
> > I think I'll disable the notification. The tokens belong to toons from multiple players; recruiters + CEO + Directors. I would prefer not to remove their tokens.
> 
> You don't need to remove their tokens, just not include them in the notification groups affiliation list. Likewise if you have in the affiliation the corp, that matches all toons of the corp. So just place day the CEO in the affiliation.

Ah I'm following now, I'll do that thanks.

Perhaps a separate topic but any idea why the character name is coming up as unknown in the notification? The link to zKill works fine.

**Comment by warlof** [comment] 2023-03-11 06:37
Close as duplicate of #680

**Closed by warlof** 2023-03-11 06:37 UTC
