### ISSUE TITLE
Wallet transaction dates and from resolves to 'corporation'

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#383] opened 2018-06-25 17:31 UTC
* **Problem**: Wallet transaction dates and the from resolves to 'corporation' 
* **Expected**: i'd expect the human readable time ... x' hrs ago
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/41865755-540949ac-78ae-11e8-9f37-53fe8c803022.png)

1) should be date
2) should show the seller?
3) should show trade partner

```
<td class="sorting_1" tabindex="0"><span data-toggle="tooltip" data-placement="top" title="" data-original-title="2018-06-23 09:30:09">Corporation</span></td>
```

* **Version Info**: 3.0.2

**Comment by leonjza** [comment] 2018-06-25 17:34
Duplicate of #302.

**Closed by leonjza** 2018-06-25 17:34 UTC
Labels: duplicate
