### ISSUE TITLE
Mining Ore Value/Amount

### ISSUE THREAD

**Issue by jim1471** [eveseat/seat#451] opened 2018-10-03 08:23 UTC
Ore value seems to be in the billions - is there a way to update the ore values?
IE:

Gleaming Spodumain | Quanity - 18 994.00 |  Volume - 303 904.00 m3 | Amount -  11 150 755 346.50 ISK

**Comment by herpaderpaldent** [comment] 2018-10-03 08:45
The issue is already fixxed but the version needs to be tagged.

**Comment by jim1471** [comment] 2018-10-03 10:30
How do i apply the fix?

**Comment by herpaderpaldent** [comment] 2018-10-03 15:31
You would have to use this commit: https://github.com/eveseat/eveapi/commit/05069c95aca6cd60f39ee5d5098e2cd6ee858b0a 

that will fix it. 

cc: @leonjza

**Comment by herpaderpaldent** [comment] 2018-10-05 05:46
HEy @jim1471 and @groniu :
Yesterdays new version includes a fix for this issue. Proceed with updating as you would normally do.

**Comment by herpaderpaldent** [comment] 2018-10-05 07:34
thank you @groniu and i want to apologize, this is my error. You will notice this error occurring with any mercoxite or ice/strontium miner. I am sorry next version will resolve this error.

**Comment by groniu** [comment] 2018-10-05 07:54
no problem , I just hate this docker thningy cant access mysql for a quick fix 
I think gonna reinstall

**Comment by groniu** [comment] 2018-10-05 09:44
I did some digging in docker 
got pass from inspect and tried to connect from inside mariadb  docker container or any other seat container like 
'docker exec -it 16e1ba586e4d  mysql -useat -p -h 172.18.0.3'
even installed client on host every time I connect i get  access denied  with seat or debian-sys-maint user

**Comment by groniu** [comment] 2018-10-08 11:39
@herpaderpaldent when this fix will be published any ETA ?

**Comment by herpaderpaldent** [comment] 2018-10-08 13:55
Honestly i can't get you an ETA since i have no power about this. 

However on your connecting to mariadb issue i can paste you a command that youll find in your documentation about how to sql export stuff as backup. Modify it to enter the shell and alter the table manually

'docker-compose exec mariadb sh -c 'exec mysqldump "$MYSQL_DATABASE" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' | gzip > seat_backup.sql.gz'

**Closed** 2018-10-09 17:20 UTC
