### ISSUE TITLE
Horizon is not finishing jobs

### ISSUE THREAD

**Issue by ItzMeJesse** [eveseat/seat#564] opened 2019-06-08 17:43 UTC
* **Problem**:  Whats wrong?
I changed my domain name and ever since my Horizon Queue is not finishing jobs.

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
Ubuntu, seat versions included in the attachments

I'm like a complete idiot at linux and this is probably easily fixed but I don't know how.

![cecf491c78526c89129d8288b5b94cf9](https://user-images.githubusercontent.com/45925778/59150532-7d2c7780-8a25-11e9-8f29-0c789ce8dc3a.png)
![horizon interface](https://user-images.githubusercontent.com/45925778/59150533-7dc50e00-8a25-11e9-85c4-b731eaafc587.png)
![queue](https://user-images.githubusercontent.com/45925778/59150534-7dc50e00-8a25-11e9-9a52-2b915806c585.png)

Kind regards
Jesse

**Comment by warlof** [comment] 2019-06-08 17:55
Hi,

You need to process a complete queue in less than 60min. All job queued for more than this time will be automatically removed/killed.

According to your average processing time (job per minute), I assume you are running on a server using hard drive. Due to the high I/O SeAT is requiring, you should consider switch to some hardware with either SSD or NVMe drives (ovh / so you start or Digital Ocean are providing such ones - but they're not alone).

You also can consider to increase the amount of Workers - but keep in mind that your Cpu must be unstressed as most as possible (the load average must be bellow the maximum of core your cpu has).

Also, you can tweak the default jobs scheduling in SeAT settings. By default, we're queueing jobs for corporations and characters every hour.

**Comment by ItzMeJesse** [comment] 2019-06-08 18:02
This is odd though because this issue started occuring only after switching a domain name but the hardware remained the same and has been working for over a year now.

**Comment by warlof** [comment] 2019-06-08 18:07
You can try to clear the queue and start from fresh using `php artisan cache:clear` command. But except if you have more things to share, I doubt the domain change anything 😉

**Comment by Geabo** [comment] 2019-06-10 18:43
Same issue after updating SeAT to the latest version today:

High number in the queue (this never reached more than a few hundred before and would clear after a few minutes).
![Screenshot_1](https://user-images.githubusercontent.com/17442707/59218005-179ad100-8b74-11e9-9fc5-22df36b1a17a.png)

I added additional workers in an attempt to get the queue down.
Running on VPS with following:
CPU: 2 vCore
RAM:2 GB
SSD: 80 GB
![Screenshot_2](https://user-images.githubusercontent.com/17442707/59218130-54ff5e80-8b74-11e9-89ab-f83795f2078f.png)

Below is a screenshot of what I get from: `docker-compose logs --tail 10 -f`
![Screenshot_3](https://user-images.githubusercontent.com/17442707/59218313-d0611000-8b74-11e9-8049-78298e457e60.png)

Not too savy on docker stuff, let me know what other information would be helpful.

**Comment by warlof** [comment] 2019-06-10 18:50
Hi @Geabo, when did you update for last ? (except today)

**Comment by Geabo** [comment] 2019-06-10 18:50
When I first spun up the server back in February

**Comment by Geabo** [comment] 2019-06-10 18:53
Update: the additional workers are catching up but a higher number of failed jobs than I'm used to seeing (usually a few per hour).

![Screenshot_1](https://user-images.githubusercontent.com/17442707/59219042-66e20100-8b76-11e9-8ae3-c853de7dd1b8.png)

**Comment by ItzMeJesse** [comment] 2019-06-10 19:31
At the domain change for me, I did update seat at the same moment.
This date was I think on the 26th of May.

**Comment by warlof** [comment] 2019-06-10 19:43
@ItzMeJesse which such specs, you can definitely bump pour worker amount to 12 or more and switch to auto balanced queue.

**Comment by ItzMeJesse** [comment] 2019-06-10 19:48
Are these settings set by the horizon.php file or are there commands for this?

**Comment by Geabo** [comment] 2019-06-10 20:54
@ItzMeJesse in `/etc/supervisor/conf.d/` change the following:

> process_name = %(program_name)s_%(process_num)02d
> ...
> numprocs=3

Then go to `/var/www/seat/vendor/laravel/horizon/config/horizon.php` and change the following at the bottom under both "environments" and "local" (not sure if both is necessary, but it worked for me):

> 'balance' => 'auto',

**Comment by ItzMeJesse** [comment] 2019-06-10 20:59
@Geabo 
By default mine looks like this:
![Seat conf](https://user-images.githubusercontent.com/45925778/59226467-58760280-8bd3-11e9-93dc-5dcb71ab85f9.png)

**Comment by Geabo** [comment] 2019-06-10 21:02
I'm not entirely sure about the auto balance. I just checked again and still have red "x"s
![Screenshot_1](https://user-images.githubusercontent.com/17442707/59226638-5175d280-8b88-11e9-967a-c4ba83c8832e.png)

**Comment by ItzMeJesse** [comment] 2019-06-10 21:17
I think that killed my supervisor?
I set the num procs to 12 and now my supervisor.sock has gone missing.
It was supposed to be 3 aaaargh.
@warlof @Geabo

**Comment by Geabo** [comment] 2019-06-10 21:25
`sudo supervisorctl update `

`sudo supervisorctl restart`

Did you run the above commands after changing conf.d?

**Comment by ItzMeJesse** [comment] 2019-06-10 21:29
Negative, I ran the supervisorctl restart then restarted the vps

**Comment by warlof** [comment] 2019-06-10 21:31
https://eveseat.github.io/docs/configuration/env_file_reference/ just the last 2

**Comment by ItzMeJesse** [comment] 2019-06-10 21:34
@warlof  Those lines are not in my .env
They end at
SUPERVISOR_RPC_ADDRESS=
SUPERVISOR_RPC_USERNAME=
SUPERVISOR_RPC_PASSWORD=nottellingyou :)
SUPERVISOR_RPC_PORT=9001
SUPERVISOR_GROUP=seat

**Comment by ItzMeJesse** [comment] 2019-06-10 21:48
Ok, The jobs are no longer paused (for now).
I will monitor the queue closely but they already give out a runtime so it's finishing them.

The issue was not enough workers to handle the load.

If it doesn't start being stupid within a couple hours I will close this topic.
Thanks for the help!

**Comment by Geabo** [comment] 2019-06-10 21:52
Did you get auto balance to work? That's bugging me know. I added the line in the .env for `QUEUE_BALANCING_MODE=auto`, but no effect.

**Comment by Geabo** [comment] 2019-06-10 21:53
Also confirming the additional workers did eventually catch up:
![Screenshot_2](https://user-images.githubusercontent.com/17442707/59229543-86395800-8b8f-11e9-9d9c-d850668660ea.png)

**Comment by ItzMeJesse** [comment] 2019-06-10 21:54
![cross](https://user-images.githubusercontent.com/45925778/59229562-05a04900-8bdb-11e9-9cca-0bf26c915174.png)

The balance still is a red cross so doubts there but it is working

**Comment by leonjza** [comment] 2019-06-11 05:27
> @ItzMeJesse in `/etc/supervisor/conf.d/` change the following:
> 
> > process_name = %(program_name)s_%(process_num)02d
> > ...
> > numprocs=3
> 

Modifying your supervisor configuration like this is not the correct way to scale workers and may have unintended side effects (mostly negative). SeAT makes use of [Horizon](https://horizon.laravel.com/) which manages the number of workers automatically, internally and relies on the single supervisor jonb for that.

That being said, we need to document this it seems, but the correct way to "increase workers" is to specify `QUEUE_WORKERS` in your `.env` file, and specifying a number. For example:

```
QUEUE_WORKERS=6
```

In code, the number of workers is read from [here](https://github.com/eveseat/web/blob/master/src/WebServiceProvider.php#L309).

**Comment by leonjza** [comment] 2019-06-11 05:28
A reference for `.env` variables may be found here: https://eveseat.github.io/docs/configuration/env_file_reference/

**Comment by ItzMeJesse** [comment] 2019-06-11 17:06
Yeah, I bumped my workers to 16 and I get waves of 15k jobs at times and they burn away at it but is this how seat intends to work?

If that is the case this topic is closed.
The problem was that my .env was outdated and didn't have all the lines of the reference.

**Comment by Geabo** [comment] 2019-06-13 15:12
I still don't feel like this is a "fix" - more of a band-aid. This issue did not appear until the latest revision, and increasing the workers does not address the root issue of waves of jobs in the queue. Sometimes the workers can keep up, sometimes they can't. I usually see a wave (increase to 20k+) and by the time it burns back down to 10K-11K another wave hits and it starts over.

![Screenshot_1](https://user-images.githubusercontent.com/17442707/59444237-5fa73700-8db2-11e9-9148-3af27cc5a5a9.png)

**Comment by leonjza** [comment] 2019-06-13 15:14
Just an update, there are plans to revert some commits where funneling that was introduced in the coming weekend.

**Comment by Geabo** [comment] 2019-06-13 15:15
Ok, is there any info (logs, metrics, diagnostics, etc.) I can provide that would help?

**Comment by jediefe** [comment] 2019-06-13 15:29
I'll just add some confirmation to the issue that is persistent since one of the last SeAT core updates. Thank you @leonjza for the feedback that this is going to be handled.

**Comment by leonjza** [comment] 2019-06-14 05:34
[eveapi 3.0.14](https://github.com/eveseat/eveapi/releases/tag/3.0.14) landed which should hopefully improve this situation. Update and let us know. Thanks @warlof for championing this.

**Comment by jediefe** [comment] 2019-06-14 08:02
Seems to work as it ran overnight without problems, which wasn't the case before.

**Comment by Geabo** [comment] 2019-06-14 15:15
Confirmed, after updating to [eveapi 3.0.14](https://github.com/eveseat/eveapi/releases/tag/3.0.14) my queue of 11k jobs cleared in under 30 mins. No more "waves" of jobs are hitting the system either. Thanks for the quick fix and dedication gentlemen!

**Comment by warlof** [comment] 2019-06-15 08:00
@Geabo what kind of jobs?

The funnel which was introduced in 3.0.12 has been removed and it's the only change which has been applied at jobs level

**Comment by ItzMeJesse** [comment] 2019-06-15 11:34
I have not witnissed a wave of 10k jobs yet but I'm sure they're still there.
15k+  jobs per hour.
These are various jobs & this has not occured since late May so there might be something else that is causing this other than the funneling.

**Comment by jediefe** [comment] 2019-06-15 11:49
How many registered users does your SeAT instance have? 15k+ jobs is a common number if there is a certain number of users. In my instance I run over 30k jobs every hour due to the number of users, and that's how it's supposed to be.

**Comment by warlof** [comment] 2019-06-15 12:07
All changes regarding jobs are listed here : https://github.com/eveseat/eveapi/commits/master

The only major change which have been introduced during May is the endpoint bump of character wallet journal.

**Comment by ItzMeJesse** [comment] 2019-06-15 12:12
I have 300 users registered so that could be the thing why so many jobs are being ran instead of last year

**Comment by jediefe** [comment] 2019-06-15 12:19
It's probably working correctly now. ;-)

**Comment by MoucceuWildfire** [comment] 2019-06-16 17:52
Nice update. Now my instance of SeAT finishes jobs within 25 mni approx instead of hour. 1300 chars registered.

**Closed** 2019-06-20 19:37 UTC
Labels: suport / help wanted
