### ISSUE TITLE
SEAT 4.0 does not store new refresh tokens when migrating from old auth to new JWT auth (v2)

### ISSUE THREAD

**Issue by stebet** [eveseat/seat#675] opened 2020-09-15 14:58 UTC
* **Problem**: SEAT 4.0 always migrates old refresh tokens and doesn't update to the new refresh token returned when upgrading takes place, causing unnecessary load on the EVE Online SSO
* **Expected**: Refresh token is updated to the new v2 refresh token.
* **Logs / Screenshots / Proof**: Contact CCP Ghostrider on Tweetfleet Slack for details.
* **Version Info**: SeAT Version 4.0.0

**Comment by stebet** [comment] 2020-09-15 14:59
As we are about to make a change to the EVE Online SSO to only allow migrating a refresh token once, this will cause SEAT auths to break unless fixed relatively quickly.

**Comment by warlof** [comment] 2020-09-16 06:12
As for now, I only spot two cases when we might not keep an updated token. All are tied to job flow and esi call :

1) if esi return a 304 because cached data based on etag are still up-to-date

2) if a job which ask to renew a token had crash during the overall process (job exception or any response between 4xx and 5xx)

https://github.com/eveseat/eveapi/blob/3327171f3bbe0d705d0b465a48175574f6b824d2/src/Jobs/EsiBase.php#L269

A patch will be sent during the day to address those two cases.

**Comment by warlof** [comment] 2020-09-27 09:11
Could be partially addressed by eveseat/eveapi#260

**Comment by rhulsker** [comment] 2020-11-19 20:02
I recently upgraded from Seat3 to Seat4, during this process it seems that all my users tokens were invalidated.  I followed all the instructions in the upgrade documentation and it seems there is no warning on that page that indicates that all tokens will be invalidated. 

I do have a database backup and a backup of the application directory is there any way to restore that will result in those tokens being useable?

**Comment by warlof** [comment] 2020-11-19 20:44
@rhulsker nope, tokens are expired. However, your data are still there.

Still working on it, tried multiple things and our last hope is that the issue is related to concurrent running jobs attempting to upgrade token at same time.

There is a fix in progress that will force token conversion during upgrade instead leaving jobs handling the task.

**Comment by rhulsker** [comment] 2020-11-19 21:54
You should probably put a warning on the upgrade instructions page.  I have now permanently lost the tokens for a few important characters which I will never be able to get back (spies who were kicked from the corp and never revoked their tokens).

**Closed** 2020-11-29 09:14 UTC
Labels: bug, complexity/high, core/auth, core/jobs, esi
