### ISSUE TITLE
Working Jobs stuck preventing queued jobs from running

### ISSUE THREAD

**Issue by Hightech1011** [eveseat/seat#67] opened 2016-02-11 08:12 UTC
I am having an issue where working jobs remain running/processing, preventing queued jobs from running.

I followed the instructions for CentOS found "https://github.com/eveseat/seat/wiki/CentOS-6.x-Installation" and made modification to fit the platform I have 'SeAT" running in. 

Details:

Hosted VPS running CentOS 6.5
Apache Version 	2.2.31
PHP 5.5.32 (cli) (built: Feb 11 2016 00:08:12)
mysql  Ver 14.14 Distrib 5.6.29, for Linux (x86_64) using  EditLine wrapper
cPanel Version 	54.0 (build 14)

All of the install process was done as root. Username were changed for the platform. Web interface work correctly and accepts APIs, but unable to pull the APIs due to hung working jobs.

Any help is appreciated. If more info is needed please let me know.

**Comment by warlof** [comment] 2016-02-11 08:17
Can you give us the exit of
php seat_path/artisan seat:admin:diagnose
iptables -L

seat_path/storage/logs/laravel.log content
supervisor status
redis status

**Comment by leonjza** [comment] 2016-02-11 08:59
Closing as duplicate of #42. Please comment there.

**Closed by leonjza** 2016-02-11 08:59 UTC
