### ISSUE TITLE
SeAT 4.0 Various Squads bugs

### ISSUE THREAD

**Issue by JohnSheppard001** [eveseat/seat#622] opened 2020-06-08 09:50 UTC
**Squads bug Report**
- Discovered a bug with filters, where if (Manual, Auto or Hidden) filters are selected (Which they are by default) it will duplicate some groups and others groups will not show up at all. However if all three filter types are not selected then I can see everything fine.

- When members click on any group (Auto, Hidden, or Manual) while either both a member or not they get a datatables error like shown below. It seems like this error is caused due to the members card trying to load with no permission to view group members I assume.
https://puu.sh/FTXID/fda228a5cb.png

- Squads seem to still show up to members even if you do not have the requirements to see it. A fix is recommended to all group types where if you do not meet the filter requirements you should not be able to see the group on the list.
**Example** if you have a recruiter group and it has a filter to a certain corp or alliance then other alliance and corporation members that are not on the filter list should not see the group or have the ability to apply to it.

- There is a bug while editing squads, it throws an error while trying to edit any existing squad. Bug shows up for trying to edit group name, description, type, or filters. Check bug call Exception below for more details.
https://flareapp.io/share/VmeNMjPQ

**Comment by warlof** [comment] 2020-06-09 06:32
Can you détail that part à little bit? I'm not able to reproduce it.

> Discovered a bug with filters, where if (Manual, Auto or Hidden) filters are selected (Which they are by default) it will duplicate some groups and others groups will not show up at all. However if all three filter types are not selected then I can see everything fine.

If you don't meet squad requirements, you are normally not able to join it. Isn't it the case? Hiding them completely, except for hidden type, isn't a good idea since doing so will avoid peeps to know how they can join it. 

> Squads seem to still show up to members even if you do not have the requirements to see it. A fix is recommended to all group types where if you do not meet the filter requirements you should not be able to see the group on the list.

**Comment by warlof** [comment] 2020-06-09 18:08
Regarding the update issue you encounter, it has been fixed with eveseat/web#441

**Comment by JohnSheppard001** [comment] 2020-06-10 04:05
> Can you détail that part à little bit? I'm not able to reproduce it.

>> Discovered a bug with filters, where if (Manual, Auto, or Hidden) filters are selected (Which they are by default) it will duplicate some groups and other groups will not show up at all. However, if all three filter types are not selected then I can see everything fine.

You can reproduce this issue by making about 9 groups, this problem only occurs when you have more than 1 page of squads. Name them 1 through 9 or anything u want then you will notice that some groups will go missing when you switch to next page and duplicate 1 or two of them

**Comment by JohnSheppard001** [comment] 2020-06-10 10:50
> Regarding the update issue you encounter, it has been fixed with [eveseat/web#441](https://github.com/eveseat/web/pull/441)

Just tested it works great!
Thanks

**Comment by JohnSheppard001** [comment] 2020-06-10 11:18
Yeah, you are correct they are not able to join if they don't meet requirements. However for bigger alliances and coalitions when they have a ton of groups having maybe the option there (As a checkbox) when creating a **Manual or Auto** group to hide group if members don't meet requirements would be nice! it helps clean things up and also keeps groups/channels hidden until requirements are met then gives you the option to join if you so choose.

I can probably work on that later and add as a feature :)


>If you don't meet squad requirements, you are normally not able to join it. Isn't it the case? Hiding them completely, except for hidden type, isn't a good idea since doing so will avoid peeps to know how they can join it.

>>Squads seem to still show up to members even if you do not have the requirements to see it. A fix is recommended to all group types where if you do not meet the filter requirements you should not be able to see the group on the list.

**Comment by JohnSheppard001** [comment] 2020-06-10 11:20
I discovered another error regarding this where if you have a user set as a moderator of a group. it does not show the members list of this particular group and also produces the same datatables error linked in the image below

> * When members click on any group (Auto, Hidden, or Manual) while either both a member or not they get a datatables error like shown below. It seems like this error is caused due to the members card trying to load with no permission to view group members I assume.
>   https://puu.sh/FTXID/fda228a5cb.png

**Comment by warlof** [comment] 2020-06-13 10:24
right, figure what was going wrong with gate `squads.kick` which was causing you troubles during squad members render.

also find why unauthorized events were not logged as expected.

**Comment by JohnSheppard001** [comment] 2020-06-14 10:56
I am not sure this is the right fix for this.

Now users have the ability to edit and kick members from squads. both one's they are a member of and one's they are not a member of. It also includes kicking people from Auto, squads.

Users now also have the ability to see members list entirely instead of just moderator and admins seeing the squad members list.

**Comment by warlof** [comment] 2020-06-14 12:08
> Now users have the ability to edit and kick members from squads. both one's they are a member of and one's they are not a member of. It also includes kicking people from Auto, squads.

Only persons able to kick a members from a squad are :
 - moderator
 - administrator

An user cannot kick himself from a squad. He need to leave it.

> Users now also have the ability to see members list entirely instead of just moderator and admins seeing the squad members list.

It has always been the case, you get access to members list as soon as you're member of a squad. Saying that, when you're in your super OpSec fleet, you see other toons, so don't ask me to hide members from squad when you're part of it :p

**Comment by JohnSheppard001** [comment] 2020-06-14 23:42
>>Now users have the ability to edit and kick members from squads. both one's they are a member of and one's they are not a member of. It also includes kicking people from Auto, squads.

>Only persons able to kick a members from a squad are :

>- moderator
>- administrator

>An user cannot kick himself from a squad. He need to leave it.

Yes, I am aware that this is how things should work which is why I am reporting that this is not how it is now after your patch and reporting it as a bug. I tested it with users with no moderator and administrator roles and they were able to kick other squad members and edit the squad details and filter.

**Comment by warlof** [comment] 2020-06-22 11:46
Just need a confirmation regarding the squads list display, but all reported point should have been addressed.

The issue will be closed next week.

**Closed** 2020-07-09 11:01 UTC
Labels: acl
