### ISSUE TITLE
Char / corporation names lacking 

### ISSUE THREAD

**Issue by DustinKincaidFerguson** [eveseat/seat#427] opened 2018-08-16 18:15 UTC
In peoples mailsor isk transfers the recipent or sender etc is listed numeracally amd not with the name of the reciever or sender. 

Its not verry helpful when finding out who sent isk to who because say, joe sent 1isk to 123456 person. Knowing that is pivital to info and security! 

Please advise

**Comment by warlof** [comment] 2018-09-09 10:31
This is a duplicate of eveseat/seat#308 but a known issue.

**Closed by warlof** 2018-09-09 10:31 UTC
