### ISSUE TITLE
Missing Structures in corporation/structures tab

### ISSUE THREAD

**Issue by ppetermann** [eveseat/seat#538] opened 2019-02-24 10:57 UTC
Expected:
- have all of a corporations anchored structures listed in the structures tab

Current Result:
- Navigation Structures, such as for example the Ansiblex Jump Gates are missing

SeAT: 
```
| Vendor          | Package Name  | Installed Version |
| --------------- | ------------- | ----------------- |
| eveseat         | api           | 3.0.6             |
| eveseat         | console       | 3.0.3             |
| eveseat         | eveapi        | 3.0.10            |
| eveseat         | notifications | 3.0.3             |
| eveseat         | services      | 3.0.5             |
| eveseat         | web           | 3.0.14            |
| finfleet        | fintension    | 0.1.2             |
| herpaderpaldent | seat-groups   | 1.6.9             |
```

**Comment by warlof** [comment] 2019-02-24 11:05
Closing as duplicate of eveseat/seat#537

**Closed by warlof** 2019-02-24 11:05 UTC
