### ISSUE TITLE
Junior Accountant Bag

### ISSUE THREAD

**Issue by AlexCo88** [eveseat/seat#602] opened 2019-11-18 22:46 UTC
Hi.
judging by the game mechanic, the rights of an associate accountant should not include viewing the corporate transaction log. In tgre I can not do this, but through SEAT I see these transactions

I would like to take part in finalizing this project

I was in a hurry, and therefore the description is scarce, you can contact me and I will provide more information

**Comment by AlexCo88** [comment] 2019-11-18 22:47
https://support.eveonline.com/hc/en-us/articles/203217712-Roles-Listing

**Comment by warlof** [comment] 2019-11-19 07:46
I @AlexCo88, I assume you're talking about the junior accountant. According to this, he shouldn't get access to the wallet journal neither - except if I'm dump - which is the case in SeAT since a really long time.

Can you confirm?

**Comment by tigranm75** [comment] 2019-11-19 17:43
I can confirm this bug. Players with ingame "Junior accountant" role has access to corporation wallet transactions in SeAT.

**Comment by AlexCo88** [comment] 2019-11-19 19:55
I confirm that a bug exists. I'm really talking about the rights of a junior accountant to view the corporate wallet operations log

**Comment by warlof** [comment] 2019-11-19 20:19
@AlexCo88 can you tell me if the junior accountant should or should not get access to Wallet Journal ?

**Comment by AlexCo88** [comment] 2019-11-20 14:12
a junior accountant should not be entitled to view the corporate wallet journal

**Comment by warlof** [comment] 2019-11-20 21:08
it has been fixed in release eveseat/web@3.0.27

**Closed by warlof** 2019-11-20 21:08 UTC
Labels: confirmed bug
