### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by marazmatik** [eveseat/seat#855] opened 2022-01-16 11:49 UTC
alliance
	1 corp Infrastructure corp
	2 corp 
	3 corp
	4 corp
	
	1 User have 2 characters in 1 and 2 corps
	2 User have 2 characters in 1 and 3 corps
	3 User have 2 characters in 1 and 4 corps

In Notifications i add in affilations 2,3,4 corps

and now i have 3 notifications in discord about structures of 1 corp

```
| Vendor   | Package Name             | Installed Version        |
| -------- | ------------------------ | ------------------------ |
| eveseat  | api                      | 4.7.0                    |
| eveseat  | console                  | 4.8.0                    |
| eveseat  | eveapi                   | 4.16.0                   |
| eveseat  | notifications            | 4.3.1                    |
| eveseat  | services                 | 4.2.0                    |
| eveseat  | web                      | 4.17.0                   |
| denngarr | seat-fitting             | 4.0.5                    |
| denngarr | seat-srp                 | 4.2.6                    |
| humunuk  | alliance-structure-mngmt | 0.5.2                    |
| kassie   | calendar                 | 4.0.5                    |
| ccp      | eve_online_sde           | sde-20211207-TRANQUILITY |
```

**Comment by warlof** [comment] 2022-01-16 12:41
Closing as duplicate of #680

**Closed by warlof** 2022-01-16 12:41 UTC
