### ISSUE TITLE
Inverse permissions not working.

### ISSUE THREAD

**Issue by Cwittofur** [eveseat/seat#365] opened 2018-06-11 01:41 UTC
I'm attempting to create a 'Recruiter' role in SeAT. I have the items I wish them to have access to and for Affiliations I have the 'Inverse' of my corp. My reasoning is because the inverse is anything that isn't my corp should be available. 

I've tried several permutations of my corp, all corps, etc. and I cannot get it to work correctly. Is there something I'm missing here? I'm using the latest 3.x version.

**Comment by leonjza** [comment] 2018-06-11 05:10
Could you elaborate what isn't working? Like the issue template says, the more details the better, please.

**Comment by Cwittofur** [comment] 2018-06-11 14:02
Apologies for the brevity of the initial request. 

the image below is what I have for my permissions. I have the corp affiliation set to Inverse, which logically would make me think any corp except for that one. And I assigned it to one user. When I impersonate that user, I am only able to see the characters associated to the user and no characters which belong to other corps. The only way I've been able to see users from other corps is to implicitly add it as an Affiliation. It wouldn't make sense to need to update affiliations each time a new corp is added for the recruiter, which is what made me conclude that it wasn't working.

![seat_permissions](https://user-images.githubusercontent.com/13065604/41236104-40b328ba-6d5e-11e8-82b5-d0c141d6241e.PNG)

**Comment by herpaderpaldent** [comment] 2018-06-11 14:04
You need to do the inverse character affiliation for what you want to achieve.

**Comment by herpaderpaldent** [comment] 2018-06-11 14:09
this is not how the ACL works. You would need to give character affiliations of characters not in your corporation. However, to limit recruitment officers to out of corp characters doesn't make sense since a recruiter might need to check a member occasionally too. Awoxing happens from within the group not as a recruit. 
There is no way to use ACL atm in the way you want to use it. My suggestion: assing all character affiliation to this role and close this issue: Works as designed.

**Comment by leonjza** [comment] 2018-06-11 16:16
Going to keep this one open. The ACL system is getting a massive rip and replace in 3.1 to better cater for these scenarios.

**Comment by NyxVxyN** [comment] 2019-03-18 01:46
Any update on this as we need this functionality, our recruiters do not need to see all of the corporation or leadership assets.

**Comment by warlof** [comment] 2019-03-18 07:29
Hi @nyxvxyn,

You should make a test with last versions as I know that ACL get some extra fixes recently.

Despite it's not refactor to gate yet though.

**Comment by herpaderpaldent** [comment] 2019-03-18 09:48
the recent fixes did not address the issue above (the recruiter role). 

* https://github.com/eveseat/web/pull/253 

One still need to inverse affiliate every character in your corporation manually

**Comment by matrimboirelle** [comment] 2019-06-03 03:49
+1 would like this to work

**Comment by warlof** [comment] 2020-04-08 14:08
Closing since new the ACL system does non longer contains inverse permissions but per permissions filters.

**Closed by warlof** 2020-04-08 14:08 UTC
Labels: 3.1, acl
