### ISSUE TITLE
Dubbling character as new member

### ISSUE THREAD

**Issue by marazmatik** [eveseat/seat#677] opened 2020-09-25 08:52 UTC
After upgrade from seat3 to seat 4 , member with some linked character see only one main person, if we enter to seat by one of the linked character, seat create it as new one. and when you try to look it when it linked we have 500 error
![error](https://user-images.githubusercontent.com/2928910/94246962-1df9bb80-ff25-11ea-9617-20e9373d0e3a.jpg)

```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.1.0                    |
| eveseat  | console                | 4.0.4                    |
| eveseat  | eveapi                 | 4.1.2                    |
| eveseat  | notifications          | 4.0.3                    |
| eveseat  | services               | 4.0.0                    |
| eveseat  | web                    | 4.2.2                    |
| denngarr | seat-fitting           | 4.0.1                    |
| denngarr | seat-srp               | 4.0.2                    |
| warlof   | seat-connector         | 2.0.2                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| warlof   | seat-teamspeak         | 5.0.0                    |
| ccp      | eve_online_sde         | sde-20200728-TRANQUILITY |
```

**Comment by warlof** [comment] 2020-09-25 16:41
Hi,

Can you send logs regarding your error 500?

**Comment by marazmatik** [comment] 2020-09-26 10:56
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Marazmatichka' for key 'users_name_unique' at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141)
[stacktrace]

**Comment by warlof** [comment] 2020-11-01 09:39
When did you get the upper message ?
After logging as "Marazmatik" or "Maramatichka" ?

I'm not able to reproduce your case from screen either, that should be an eager case not handled in the 3 to 4 migration, I don't know what it could be for now :(

Did you alter your EVE Application key with the version change ?

**Comment by Crypta-Eve** [comment] 2024-11-15 05:14
Closing based on age

**Closed by Crypta-Eve** 2024-11-15 05:14 UTC
Labels: bug, core/auth, complexity/high
