### ISSUE TITLE
Mining Ledger copy paste safe ?

### ISSUE THREAD

**Issue by Taiphoz** [eveseat/seat#580] opened 2019-08-20 22:47 UTC
the currency format on for example the mining ledger does not have comma's, and your appending ISK and m3 to the end of values, this means if we try and select all copy paste to a google spread sheet we cant automatically convert the values to currencies we need to strip the white space, then strip out the ISK and m3 text.

Since eve is a massively spread sheet happy game it would be nice if this ledger, and other parts of the site were more compatible with copy and pasting the data into spread sheets.

**Comment by warlof** [comment] 2020-04-08 13:48
Closing this one since it's a duplicate of eveseat/seat#469

**Closed by warlof** 2020-04-08 13:48 UTC
Labels: good first issue, ui, wishlist
