### ISSUE TITLE
Datatables Ajax Error

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#473] opened 2018-11-07 23:06 UTC
When loading all characters from the menu option the following error is given.

DataTables warning: table id=character-list - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by herpaderpaldent** [comment] 2018-11-07 23:11
1. Probably it is caused by you, using admin in your user_group. Congratulation you are one special snowflake
2. There is a fix for this, we need tagging or you checking it out: https://github.com/eveseat/web/commit/4115a79472f1cf4d7e775ddf2f7bbc4cd09171a7

**Closed** 2018-11-25 20:39 UTC
