### ISSUE TITLE
[BUG] Wrong fuel consumption info for citadel with bonuses

### ISSUE THREAD

**Issue by tigranm75** [eveseat/seat#806] opened 2021-04-23 11:48 UTC
Problem: citadel with bonuses (like Fortizar) didn't count right fuel consumption amount. In my case shown 10 fuel blocks per hour.
Expected: 7.5 fuel blocks per hour

Version Info:
```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.5.0                    |
| eveseat  | console                | 4.8.0                    |
| eveseat  | eveapi                 | 4.11.0                   |
| eveseat  | notifications          | 4.3.1                    |
| eveseat  | services               | 4.2.0                    |
| eveseat  | web                    | 4.12.2                   |
| denngarr | seat-fitting           | 4.0.5                    |
| denngarr | seat-srp               | 4.1.0                    |
| kassie   | calendar               | 4.0.3                    |
| warlof   | seat-connector         | 2.3.0                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| warlof   | seat-teamspeak         | 5.1.0                    |
| ccp      | eve_online_sde         | sde-20210310-TRANQUILITY |
```
<img width="797" alt="Снимок экрана 2021-04-23 в 13 45 41" src="https://user-images.githubusercontent.com/52424948/115866649-42296680-a43a-11eb-818f-ece1c2cd9217.png">
<img width="799" alt="Снимок экрана 2021-04-23 в 13 45 20" src="https://user-images.githubusercontent.com/52424948/115866653-435a9380-a43a-11eb-9ea1-e9fc4ba3f10e.png">

**Comment by warlof** [comment] 2021-04-23 11:53
This is a duplicate of #789

**Closed by warlof** 2021-04-23 11:53 UTC
