### ISSUE TITLE
Reassigning main character of group leaves inconsistency

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#535] opened 2019-02-15 14:38 UTC
Situation: User registered in Seat, ended up creating two usergroups:
Char A
Char B
Char C

Char X
Char Y

* **Problem**: 
After reassigning the Character X to the group with ABC, we end up with Char X moved over to the group with ABC. Character Y however keeps showing it has Char X as main character

![image](https://user-images.githubusercontent.com/25641678/52862534-c3d42a00-3135-11e9-8010-e58ce78faf43.png)

* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/25641678/52862555-cf275580-3135-11e9-9af1-c2eee6e89236.png)

**Comment by Fundaris** [comment] 2019-02-15 15:24
Duplicate of #494 next time use search!

**Comment by herpaderpaldent** [comment] 2019-02-15 15:33
Not really a duplication of the mentioned ticket but we / at least i am aware of this: https://github.com/eveseat/web/pull/231#issuecomment-437004224 

I wasn't able to resolve this with my PR but i would definetly add this as a known bug/limitation

**Comment by kwazulueve** [comment] 2019-02-15 16:20
@Fundaris It is not a duplicate or extension of your ticket. And putting multiple changes in one ticket delays releases.

**Comment by Eingang** [comment] 2019-02-15 19:30
Creation of multiple accounts by mistake frequently happens in SeAT and Alliance Auth for two reasons: 

1. Adding additional pilot later: Someone's returned to add a new pilot some time after putting in their initial pilot(s) and neglects to log in first as a registered user. 

1. Additional pilot isn't selectable on EvE SSO permissions grant page: Someone's registering multiple pilots using "Link Character" but they don't realize they need to click `Cancel` on the EvE SSO permissions  grant page to force an EvE account login dialogue box if the pilot they want to add isn't visible.

Since users can't easily delete their own pilots or user accounts to fix this on their own, that means either living with multiple accounts or having an admin fix it. I need reasonably accurate people counts and CEOs/admins need to be sure that when someone's left corp, they've taken all their alts with them. The mapping of those alts to mains for many is the SeAT user group affiliation. I therefore find myself tidying up accidents like this commonly.

It's a reasonable expectation that an application-provided tool for group reassign/merge would append a copy of the data from the source user group to the destination user group, do whatever's required when adding additional users to a user group, and then cleanly remove any data related to the now-superfluous source user group. Having "hanging data" or inconsistent data requiring manual SQL table operations isn't expected and is beyond the capabilities of many CEOs/corps/groups who were otherwise able to follow the docker installation instructions.

**Comment by tohuw** [comment] 2019-07-09 08:33
Hello, just curious if there's progress towards a fix on this bug @warlof @herpaderpaldent

**Comment by warlof** [comment] 2019-07-09 10:21
Not yet no

**Closed** 2019-11-16 18:28 UTC
Labels: confirmed bug
