### ISSUE TITLE
Feature request : Citadel fuel block count / monthly block need

### ISSUE THREAD

**Issue by ncc-1709** [eveseat/seat#403] opened 2018-07-16 15:30 UTC
Similar to the starbase fuel counter 
a requires for (selectable 1 week, 1 month, 3 month, 6 month 1 year) fuel block need  section 

it shows the estimated offline timer, and knows what is fitted, the values of which are known.  so should be able to have an estimated fuel blocks in side, and requirement to last x time

**Comment by herpaderpaldent** [comment] 2018-07-16 15:37
other then the starbase the esi scructure endpoint doesn't deliver this out of the box: https://esi.evetech.net/ui/#/Corporation/get_corporations_corporation_id_structures 

it is doable but we would need to iterate over the used services (market/clonebay etc) and check if they are online or not. So it is not so easy as you'd expect.
I'd definetively do it on the backlog but wouldn't expect some work on it soon. Other things for 3.1 are by far more important. The expiry helps you already a lot and you as owner can view how much fuel is consumed and do your own math.

**Comment by leonjza** [comment] 2018-07-29 07:08
As @herpaderpaldent said, this is a little harder than just reading and interpreting the information available via ESI. I also don't think we would get to this anytime soon, but I'll keep this open as a wishlist item.

**Comment by warlof** [comment] 2018-09-11 18:16
Closing as duplicate of eveseat/seat#211

**Closed by warlof** 2018-09-11 18:16 UTC
Labels: wishlist
